apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "scc-admin-frontend.fullname" . }}-deploy-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "20"
spec:
  template:
    spec:
      serviceAccountName: {{ include "scc-admin-frontend.serviceAccountName" . }}-deploy-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "alpine"
          imagePullPolicy: IfNotPresent
          command: ["pwd"]
          env:
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
            - name: AWS_REGION
              value: ap-northeast-2
            - name: AWS_ROLE_ARN
              value: "{{ .Values.deploySecret.awsRoleArn }}"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          volumeMounts:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
            - name: config-volume
              mountPath: /app/conf
              readOnly: true
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
        - name: config-volume
          configMap:
            name: {{ include "scc-admin-frontend.fullname" . }}
      restartPolicy: Never
  backoffLimit: 3
